engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
        - javascript
ratings:
  paths:
  - src/**
  - spec/**
  - examples/face/*.js
exclude_paths:
  - examples/lib/**
  - examples/face/rabbit.js
