engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
  - rabbit.js
  - spec/**
  - examples/**
exclude_paths:
  - canteen.min.js
  - jquery.js
  - lib/**
